[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chaste_codegen_sbml"
dynamic = ["version"]

description = "Chaste C++ code generation from SBML"

readme = "README.md"
license = { file = "LICENSE" }

authors = [{ name = "Kwabena Amponsah" }, { name = "James Osborne" }]

requires-python = ">=3.9"

dependencies = ["Jinja2 >=3.0,<4", "python-libsbml >=5.20,<6"]

[project.optional-dependencies]
dev = [
  "flake8",
  "flake8-bugbear",
  "isort",
  "Jinja2>=3.1",
  "pytest",
  "python-libsbml>=5.20",
]

[project.scripts]
chaste_codegen_sbml = "chaste_codegen_sbml.__main__:main"

[project.urls]
source = "https://github.com/Chaste/chaste-codegen-sbml"

[tool.setuptools_scm]
version_file = "chaste_codegen_sbml/_version.py"

[tool.black]
line-length = 100
target-version = ["py39", "py310", "py311", "py312", "py313"]
extend-exclude = """
(
  SBMLRefModels
  | templates/
  | ^/venv/
)
"""

[tool.isort]
known_first_party = "chaste_codegen_sbml"
extend_skip = ["SBMLRefModels", "templates", "venv"]
profile = "black"
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
ensure_newline_before_comments = "True"
line_length = 100
