//! @file
//!
//! This source file was generated from SBML by chaste_codegen_sbml version {{converter_version}}
//!
//! Model: {{model_name}}
//!
//! Processed by chaste_codegen_sbml: https://github.com/Chaste/chaste-codegen-sbml
//!     (translator: chaste_codegen_sbml, model type: {{model_type}})
//! on {{generation_date}}
//!
//! <autogenerated>