#
# Sphinx documentation build configuration for chaste-sbml.
#

# -- General configuration ------------------------------------------------

extensions = [
    "sphinx.ext.mathjax",
    "sphinx.ext.githubpages",
    "myst_parser",  # author pages in Markdown instead of reStructuredText
    "sphinx_copybutton",  # add a copy button to code blocks
]

# MyST (Markdown) niceties: ::: fenced directives and (# anchor)= header targets.
myst_enable_extensions = ["colon_fence", "deflist"]
myst_heading_anchors = 3

# Strip common interactive prompts from the copied text so pasting a shell or
# Python snippet doesn't include the "$ " / ">>> " markers.
copybutton_prompt_text = r">>> |\.\.\. |\$ "
copybutton_prompt_is_regexp = True

templates_path = []

# The suffix(es) of source filenames.
source_suffix = {".rst": "restructuredtext", ".md": "markdown"}

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "chaste-sbml"
copyright = "2024, Chaste Developers"
author = "Chaste Developers <chaste-users@maillist.ox.ac.uk>"

# The version info, used as replacement for |version| and |release|.
# Single-sourced from the installed package metadata (which setuptools-scm
# populates), so it can never drift from the release; falls back to "0.0.0"
# for a bare, uninstalled checkout.


def _project_version() -> str:
    from importlib import metadata

    try:
        return metadata.version("chaste-sbml")
    except metadata.PackageNotFoundError:
        return "0.0.0"


# The full version, including alpha/beta/rc tags.
release = _project_version()
# The short X.Y version.
version = ".".join(release.split(".")[:2])

# The language for content autogenerated by Sphinx.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.
html_theme = "furo"

# Project title shown in the sidebar.
html_title = f"{project} documentation"

# Add any paths that contain custom static files (such as style sheets) here.
html_static_path = []


# -- Options for HTMLHelp output ------------------------------------------

htmlhelp_basename = "chaste-codegen-sbmldoc"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {}

latex_documents = [
    (master_doc, "chaste-sbml.tex", "chaste-sbml Documentation", author, "manual"),
]


# -- Options for manual page output ---------------------------------------

man_pages = [(master_doc, "chaste-sbml", "chaste-sbml Documentation", [author], 1)]


# -- Options for Texinfo output -------------------------------------------

texinfo_documents = [
    (
        master_doc,
        "chaste-sbml",
        "chaste-sbml Documentation",
        author,
        "chaste-sbml",
        "Import SBML models into Chaste as C++ code.",
        "Miscellaneous",
    ),
]
